
User.create(id:1, name: "joaocarlos", email: "joao@gmail.com", password: "12345678", is_admin: true, bio: "Sou o João Carlos, sou jornalista esportivo.")
User.create(id:2, name: "mariaclara", email: "maria@gmail.com", password: "12345678", is_admin: true, bio: "Sou a Maria Clara e adoro futebol.")
User.create(id:3, name: "pedropaulo", email: "pedro@gmail.com", password: "12345678", is_admin: false, bio: "Sou o Pedro Paulo e sou fanático pelo Gama FC.")
User.create(id:4, name: "leopcortes", email: "leo@gmail.com", password:"12345678", is_admin: true, bio: "Sou o Leonardo Côrtes e acho que o Flamengo vai ganhar a libertadores.")
User.create(id:5, name: "gabrielmarques", email: "marques@gmail.com", password:"12345678", is_admin: true, bio: "Sou o Gabriel Marques e jogo bola desde pequeno.")

User.find_by(name:"joaocarlos").profile_picture.attach(io: File.open('./public/joao.png'), filename:('joao.png'))
User.find_by(name:"mariaclara").profile_picture.attach(io: File.open('./public/maria.png'), filename:('maria.png'))
User.find_by(name:"pedropaulo").profile_picture.attach(io: File.open('./public/pedro.png'), filename:('pedro.png'))

Post.create(id:1, title: "Inter avança, com justiça, e mostra que fora de casa River não é tudo isso", content: "O Inter soube explorar isso e já deveria ter avançado sem disputa de penais, inclusive teve um pênalti não assinalado. E que diferença da equipe de Eduardo Coudet para o que Mano Menezes escalava!", user_id: 1)
Post.create(id:2, title: "Pênalti da Inglaterra atingiu 111km/h e superou marca da Premier League", content: "A atacante Chloe Kelly colocou a Inglaterra nas quartas de final da Copa do Mundo feminina e impressionou com a velocidade da cobrança do pênalti. O chute da jogadora do Manchester City atingiu impressionantes 111km/h. Ela conveteu a última penalidade classificando a atual campeã europeia para as quartas do Mundial feminino.", user_id: 1)
Post.create(id:3, title: "Falta de critério da arbitragem faz o Santos ser derrotado pelo São Paulo", content: "Mais uma vez (e são muitas) a arbitragem tornou-se o tema central depois de uma partida de futebol aqui no Brasil. Nossa arbitragem é fraca, infelizmente. Árbitros mal preparados, sem personalidade, suscetíveis a todo o tipo de pressão porque têm receio de tudo e de todos. E o resultado é tudo o que vemos depois que a maioria das partidas terminam: pouco se fala do jogo; muito se reclama da precariedade da nossa arbitragem.", user_id: 2)
Post.create(id:4, title: "Lukaku nem chegou e torcida da Juventus já faz protestos contra ele", content: "A possível transferência de Romelu Lukaku para a Juventus ainda não aconteceu, mas os torcedores já fizeram questão de mostrar que não estão muito felizes com a sua chegada. O jogador, muito vinculado à Inter de Milão, tem sido chamado de traidor pelos torcedores do clube nerazzurro e ainda está longe de conquistar a torcida dos bianconeri.", user_id: 2)
Post.create(id:5, title: "Violência no futebol cresce e nossa incapacidade de lidar com isso é cada vez mais nítida", content: "O futebol tem tido semanas muito tristes recentemente. Uma escalada de violência vem crescendo e as coisas parecem cada vez mais fora do controle. Pedradas em ônibus em Salvador e Porto Alegre, briga entre corintianos e são-paulinos no metrô e, principalmente, a batalha campal no México que chocou o mundo inteiro com suas imagens.", user_id: 4)
Post.create(id:6, title: "BVB planeja teste secreto antes do início da Bundesliga", content: "O Borussia de Dortmund recentemente venceu por 3-1 contra o Ajax. A nova contratação Felix Nmecha fez o BVB comemorar. O jogo havia sido anunciado pelo clube como o último ensaio antes do início da temporada, mas o BVB planeja um teste secreto antes do início da Bundesliga, conforme noticiou o Ruhr Nachrichten. De acordo com a fonte, o BVB enfrentará o Preußen Münster, da terceira divisão, um dia após o jogo pela Copa DFB no dia 12 de agosto. O jogo deve decorrer à porta fechada.", user_id: 5)
Post.create(id:7, title: "Atlético Madrid inscreve João Félix na La Liga: Barcelona tem apenas 12 jogadores", content: "Na página oficial da La Liga é possível ver os plantéis regularizados dos 20 clubes que vão disputar o campeonato espanhol. João Félix figura entre os inscritos pelo Atlético Madrid, tendo ficado com a camisola 18.", user_id: 4)
Post.create(id:8, title: "LA LIGA irá 'misturar real e virtual' com câmeras de EA Sports FC 24", content: "A LA LIGA terá câmeras que simulam ângulos de video game na temporada 2023/2024, parecido com o gameplay de EA Sports FC 24 (antigo FIFA). A tecnologia é uma parceria da entidade com a EA Sports, principal patrocinadora do campeonato espanhol de futebol. Em evento realizado ontem (08), em São Paulo (SP), Daniel Alonso, representante de LA LIGA no Brasil, explicou que as partidas terão imagens especiais em momentos como bolas paradas.", user_id: 4)
Post.create(id:9, title: "Neymar e Verratti estão fora dos planos do PSG, diz emissora RMCSport", content: "De acordo com o jornal L'Equipe Neymar comunicou que deseja deixar o clube. E um retorno ao Barcelona seria seu principal desejo, mas é improvável devido a situação financeira do clube espanhol. O Chelsea manifestou interesse em fevereiro e é uma alternativa, mas também corre por fora. Segundo o L'Equipe, o Al-Hilal fez uma proposta ao brasileiro esta semana. A MLS, nos Estados Unidos, é outro caminho.", user_id: 5)
Post.create(id:10,title: "Mbappé está fora de estreia do PSG na Ligue 1 e pode desfalcar equipe por longo período como punição", content: "Kylian Mbappé não estará em campo na estreia do PSG na Ligue 1, contra o Lorient, no Parque dos Príncipes, no sábado (12), disseram fontes à ESPN. Ainda de acordo com a reportagem, Mbappé pode perder todos os jogos do PSG em agosto como punição. O craque não treinou com o time principal sob o comando do novo técnico Luis Enrique em meio a uma disputa contratual existente com o clube.", user_id: 5)

Category.create(id:1, name: "La Liga")
Category.create(id:2, name: "Bundesliga")
Category.create(id:3, name: "Brasileirão")
Category.create(id:4, name: "Premier League")
Category.create(id:5, name: "Ligue 1")
Category.create(id:6, name: "Serie A")

PostCategory.create(id:1, post_id: 1, category_id: 3)
PostCategory.create(id:2, post_id: 2, category_id: 4)
PostCategory.create(id:3, post_id: 3, category_id: 3)
PostCategory.create(id:4, post_id: 4, category_id: 6)
PostCategory.create(id:5, post_id: 5, category_id: 3)
PostCategory.create(id:6, post_id: 6, category_id: 2)
PostCategory.create(id:7, post_id: 7, category_id: 1)
PostCategory.create(id:8, post_id: 8, category_id: 1)
PostCategory.create(id:9, post_id: 9, category_id: 5)
PostCategory.create(id:10,post_id: 10,category_id: 5)

Upvote.create(id:1,  status: true, post_id: 1, user_id: 2)
Upvote.create(id:2,  status: true, post_id: 1, user_id: 3)
Upvote.create(id:3,  status: true, post_id: 2, user_id: 1)
Upvote.create(id:4,  status: true, post_id: 2, user_id: 3)
Upvote.create(id:5,  status: true, post_id: 3, user_id: 1)
Upvote.create(id:6,  status: true, post_id: 3, user_id: 4)
Upvote.create(id:7,  status: true, post_id: 4, user_id: 5)
Upvote.create(id:8,  status: true, post_id: 4, user_id: 3)
Upvote.create(id:9,  status: true, post_id: 5, user_id: 3)
Upvote.create(id:10, status: true, post_id: 5, user_id: 1)
Upvote.create(id:11, status: true, post_id: 6, user_id: 5)
Upvote.create(id:12, status: true, post_id: 6, user_id: 4)
Upvote.create(id:13, status: true, post_id: 7, user_id: 1)
Upvote.create(id:14, status: true, post_id: 7, user_id: 4)
Upvote.create(id:15, status: true, post_id: 8, user_id: 1)
Upvote.create(id:16, status: true, post_id: 8, user_id: 5)
Upvote.create(id:17, status: true, post_id: 9, user_id: 2)
Upvote.create(id:18, status: true, post_id: 9, user_id: 3)
Upvote.create(id:19, status: true, post_id: 10,user_id: 1)
Upvote.create(id:20, status: true, post_id: 10,user_id: 2)
Upvote.create(id:21, status: true, post_id: 2, user_id: 4)
Upvote.create(id:22, status: true, post_id: 4, user_id: 5)
Upvote.create(id:23, status: true, post_id: 6, user_id: 3)
Upvote.create(id:24, status: true, post_id: 8, user_id: 5)

Comment.create(id:1, content: "Emoção até o último segundo.", post_id: 1, user_id: 5)
Comment.create(id:2, content: "Rochet salvou o dia.", post_id: 1, user_id: 4)
Comment.create(id:3, content: "Uau, impressionante.", post_id: 2, user_id: 3)
Comment.create(id:4, content: "Essa Copa feminana está incrível.", post_id: 2, user_id: 1)
Comment.create(id:5, content: "Até quando?!", post_id: 3, user_id: 4)
Comment.create(id:6, content: "Isso é um absurdo.", post_id: 3, user_id: 2)
Comment.create(id:7, content: "Se eu fosse torcedora da Juventus também estaria furiosa.", post_id: 4, user_id: 2)
Comment.create(id:8, content: "Achei uma ótima contratação.", post_id: 4, user_id: 5)
Comment.create(id:9, content: "Isso tem que acabar!", post_id: 5, user_id: 3)
Comment.create(id:10,content: "Muito triste, precisamos fazer algo para mudar.", post_id: 5, user_id: 2)
Comment.create(id:11,content: "Esse ano já é do Borussia.", post_id: 6, user_id: 2)
Comment.create(id:12,content: "A muralha amarela vai ficar triste vendo o Bayern ganhar tudo.", post_id: 6, user_id: 3)
Comment.create(id:13,content: "So ó Neymar pra salvar esse Barça.", post_id: 7, user_id: 4)
Comment.create(id:14,content: "João Felix tem muito potencial.", post_id: 7, user_id: 5)
Comment.create(id:15,content: "A tecnologia é incrível.", post_id: 8, user_id: 4)
Comment.create(id:16,content: "Isso vai aumentar muito a imersão do torcedor.", post_id: 8, user_id: 2)
Comment.create(id:17,content: "PSG é uma bagunça.", post_id: 9, user_id: 1)
Comment.create(id:18,content: "Todo esse dinheiro gasto pra não ganhar quase nada.", post_id: 9, user_id: 3)
Comment.create(id:19,content: "Como que recusa 1.6 bilhão de reais.", post_id: 10,user_id: 4)
Comment.create(id:20,content: "Mbappe fez certo, não vale a pena gastar seu auge na Arábia.", post_id: 10,user_id: 1)
